# Generated by Django 3.1.6 on 2021-02-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20210224_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonEntity_temp',
        ),
    ]
