# Generated by Django 3.1.6 on 2021-02-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20210224_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Pokemon',
            new_name='pokemon',
        ),
    ]
