# Generated by Django 3.1.7 on 2021-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20210224_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название элемента')),
                ('element_type', models.ManyToManyField(to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
