# Generated by Django 3.1.7 on 2021-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_pokemonelementtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='element_type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
    ]
